BaseUrl= "http://lowwor.com/"
LanguageCode= "zh-CN"
Title= "Lowwor's Blog"
paginate = 5
DisqusShortname = "lowwor"
Copyright = "All rights reserved - 2016"
canonifyurls = true

[params]
  description = "人的一切痛苦，本质上都是源于对自己无能的愤怒。"
  cover = "images/cover.jpg"
  author = "Lowwor"
  authorlocation = "Guangdong, China"
  authorwebsite = "http://lowwor.com"
  bio= "I am a Android developer."
  #logo = "images/logo.png"
  googleAnalyticsUserID = "UA-70800251-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..." 
  githubName = "lowwor"
  twitterName = "lowwor"
  # facebookName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  #url = "/"