name = "Rowwol"
license = "MIT"
licenselink = "https://github.com/lowwor/hugo-theme-rowwol/blob/master/LICENSE.md"
description = "Modified Casper theme from Ghost Foundation"
homepage = "http://lowwor.com/"
tags = ["blog"]
features = ["disqus", "google analytics","share"]
min_version=0.14

[author]
  name = "Lowwor"
  homepage = "http://lowwor.com"

[original]
  name = "Casper"
  homepage = "https://github.com/TryGhost/Casper"
  repo = "https://github.com/TryGhost/Casper"
